### ISSUE TITLE
Require CSRF when api_view(('POST')) on 0.1.5, but not in 0.1.4

### ISSUE THREAD

**Issue by Artasov** [em1208/adrf#32]
https://github.com/Artasov/xlartas
My project work correctly in version `0.1.4`. In `0.1.5` csrf is required for any post requests. Why?. What has changed in these versions.
An example of a controller... 1 of... I checked several times, changed the versions, and everything `breaks on 0.1.5`.
`In apps/shop/controllers/software/software_test_activate_current_user.`
```python
@api_view(('POST',))
@permission_classes([IsAuthenticated])
async def software_test_activate_current_user(request) -> Response:
     pass
```

If you are interested in testing, then it is enough to start the project:
```python
python --version
> python 3.11.6
python -m vev venv
venv/Scripts/activate
git clone https://github.com/Artasov/xlartas

rename THE TEMPLATE .env.prod > .env.prod
change
DEBUG=1
DEV=1
HTTPS=0


cd xlartas
cd frontend
npm install
npm run build
cd ..
cd backend
pip install -r requirements.txt
python manage.py migrate
python manage.py runserver
```

**Comment by em1208** [comment]
I added new tests for your use case and it is working properly. I can't comment on your setup. Since you have issues with CSRF I suggest you to look at this resource https://www.django-rest-framework.org/topics/ajax-csrf-cors/ to help you debug the issue. I'm closing this issue but feel free to post a reproducible sample code that shows the error.
